---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: demo-app:1.0.0
    volumeMounts:
    - name: config-volume
      mountPath: /path/to/config
  volumes:
  - name: config-volume
    configMap:
      name: CONFIGMAP_PARAM