---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: main-container
    image: demo-app:1.0.0
  - name: other-container
    image: multicontainerother-container
    command: ["sh", "-c", "echo 'Hello from other container!'"]
  - name: other-container
    image: demo-app:1.0.1
    command: ["sh", "-c", "echo 'Hello from updated demo-app container!'"]