---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: demo-app:1.0.0
    env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: secret-env
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: secret-env
          key: password