---
apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
  - name: app
    image: demo-app:1.0.0
    livenessProbe:
      exec:
        command:
        - echo
        - "hello"
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 2